/**
 * Render QcFullReport → qc-reports/qc-report.md
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { QcFullReport, QcStageResult, QcIssue, QC_CONFIG } from './types';

const SEVERITY_ICON: Record<string, string> = {
    critical: '🔴',
    error: '🟠',
    warning: '🟡',
    info: '🔵',
};

function formatIssue(i: QcIssue): string {
    const icon = SEVERITY_ICON[i.severity] || '⚪';
    const loc = i.file
        ? `\`${i.file}${i.line ? ':' + i.line : ''}\``
        : i.url
            ? `\`${i.url}\`${i.httpStatus ? ` (HTTP ${i.httpStatus})` : ''}`
            : '';
    const detail = i.detail ? `\n    > ${i.detail.replace(/\n/g, '\n    > ').slice(0, 600)}` : '';
    return `- ${icon} **${i.title}** ${loc}${detail}`;
}

function formatStage(s: QcStageResult): string {
    const titleMap = { static: 'Static checks', api: 'API contract', ui: 'UI smoke test' };
    const pct = s.totalChecked > 0 ? Math.round((s.passed / s.totalChecked) * 100) : 0;
    let md = `## ${titleMap[s.stage]}\n\n`;
    md += `- **Tổng check**: ${s.totalChecked}\n`;
    md += `- **Pass**: ${s.passed} (${pct}%)\n`;
    md += `- **Fail**: ${s.failed}\n`;
    md += `- **Thời gian**: ${(s.durationMs / 1000).toFixed(1)}s\n`;
    md += `- **Issues**: ${s.issues.length}\n\n`;

    if (s.issues.length === 0) {
        md += '✅ Không phát hiện vấn đề nào.\n\n';
        return md;
    }

    const bySeverity: Record<string, QcIssue[]> = { critical: [], error: [], warning: [], info: [] };
    for (const i of s.issues) bySeverity[i.severity]?.push(i);

    for (const sev of ['critical', 'error', 'warning', 'info'] as const) {
        const list = bySeverity[sev];
        if (list.length === 0) continue;
        md += `### ${SEVERITY_ICON[sev]} ${sev.toUpperCase()} (${list.length})\n\n`;
        md += list.map(formatIssue).join('\n') + '\n\n';
    }
    return md;
}

export function renderReport(report: QcFullReport): string {
    let md = '# 🧪 EHealth QC Report\n\n';
    md += `**Sinh lúc**: ${report.finishedAt}\n\n`;
    md += `**Thời gian**: ${(report.durationMs / 1000).toFixed(1)}s\n\n`;

    md += '## Tóm tắt\n\n';
    md += `| Mức | Số lượng |\n|---|---|\n`;
    md += `| 🔴 Critical | ${report.summary.critical} |\n`;
    md += `| 🟠 Error | ${report.summary.errors} |\n`;
    md += `| 🟡 Warning | ${report.summary.warnings} |\n`;
    md += `| **Tổng** | **${report.summary.totalIssues}** |\n\n`;

    if (report.summary.totalIssues === 0) {
        md += '🎉 **Toàn bộ kiểm tra PASS. Không có vấn đề nào.**\n\n';
    }

    for (const s of report.stages) md += formatStage(s);

    md += '---\n\n';
    md += '> Generated by `npm run qc:all`\n';
    return md;
}

export function writeReport(report: QcFullReport): string {
    const md = renderReport(report);
    const dir = QC_CONFIG.reportDir;
    mkdirSync(dir, { recursive: true });
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const latest = join(dir, 'qc-report.md');
    const snapshot = join(dir, `qc-report-${timestamp}.md`);
    const jsonPath = join(dir, 'qc-report.json');
    writeFileSync(latest, md);
    writeFileSync(snapshot, md);
    writeFileSync(jsonPath, JSON.stringify(report, null, 2));
    return latest;
}
